# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'attrDialog2.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(675, 481)
        self.line = QtWidgets.QFrame(Dialog)
        self.line.setGeometry(QtCore.QRect(9, 20, 641, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(9, 10, 481, 16))
        self.label.setObjectName("label")
        self.tabWidget = QtWidgets.QTableWidget(Dialog)
        self.tabWidget.setGeometry(QtCore.QRect(10, 40, 531, 381))
        self.tabWidget.setObjectName("tabWidget")
        self.tabWidget.setColumnCount(0)
        self.tabWidget.setRowCount(0)
        self.tabWidget.horizontalHeader().setStretchLastSection(True)
        self.line_3 = QtWidgets.QFrame(Dialog)
        self.line_3.setGeometry(QtCore.QRect(9, 536, 269, 16))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.ok_btn = QtWidgets.QPushButton(Dialog)
        self.ok_btn.setGeometry(QtCore.QRect(370, 430, 75, 23))
        self.ok_btn.setObjectName("ok_btn")
        self.layoutWidget = QtWidgets.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 2, 2))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.par_btn = QtWidgets.QPushButton(Dialog)
        self.par_btn.setGeometry(QtCore.QRect(10, 430, 75, 23))
        self.par_btn.setObjectName("par_btn")
        self.cancel_btn = QtWidgets.QPushButton(Dialog)
        self.cancel_btn.setGeometry(QtCore.QRect(460, 430, 75, 23))
        self.cancel_btn.setObjectName("cancel_btn")
        self.reset_btn = QtWidgets.QPushButton(Dialog)
        self.reset_btn.setGeometry(QtCore.QRect(280, 430, 75, 23))
        self.reset_btn.setObjectName("reset_btn")
        self.recalc_btn = QtWidgets.QPushButton(Dialog)
        self.recalc_btn.setGeometry(QtCore.QRect(550, 70, 51, 23))
        self.recalc_btn.setObjectName("recalc_btn")
        self.pick_btn = QtWidgets.QPushButton(Dialog)
        self.pick_btn.setGeometry(QtCore.QRect(550, 110, 51, 23))
        self.pick_btn.setObjectName("pick_btn")
        self.edit_id_btn = QtWidgets.QPushButton(Dialog)
        self.edit_id_btn.setGeometry(QtCore.QRect(600, 70, 51, 23))
        self.edit_id_btn.setObjectName("edit_id_btn")
        self.edit_name_btn = QtWidgets.QPushButton(Dialog)
        self.edit_name_btn.setGeometry(QtCore.QRect(600, 110, 51, 23))
        self.edit_name_btn.setObjectName("edit_name_btn")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Cross Board Tool"))
        self.label.setText(_translate("Dialog", "属性信息："))
        self.ok_btn.setText(_translate("Dialog", "提交"))
        self.par_btn.setText(_translate("Dialog", "参数配置"))
        self.cancel_btn.setText(_translate("Dialog", "取消"))
        self.reset_btn.setText(_translate("Dialog", "重置"))
        self.recalc_btn.setText(_translate("Dialog", "哈希"))
        self.pick_btn.setText(_translate("Dialog", "拾取"))
        self.edit_id_btn.setText(_translate("Dialog", "编辑"))
        self.edit_name_btn.setText(_translate("Dialog", "编辑"))
