# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'linkListDockWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_roadListDockWidget(object):
    def setupUi(self, roadListDockWidget):
        roadListDockWidget.setObjectName("roadListDockWidget")
        roadListDockWidget.resize(404, 524)
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.gridLayout = QtWidgets.QGridLayout(self.dockWidgetContents)
        self.gridLayout.setObjectName("gridLayout")
        self.up_link = QtWidgets.QPushButton(self.dockWidgetContents)
        self.up_link.setObjectName("up_link")
        self.gridLayout.addWidget(self.up_link, 0, 3, 1, 1)
        self.pick_link = QtWidgets.QPushButton(self.dockWidgetContents)
        self.pick_link.setObjectName("pick_link")
        self.gridLayout.addWidget(self.pick_link, 0, 1, 1, 1)
        self.down_link = QtWidgets.QPushButton(self.dockWidgetContents)
        self.down_link.setObjectName("down_link")
        self.gridLayout.addWidget(self.down_link, 0, 4, 1, 1)
        self.del_link = QtWidgets.QPushButton(self.dockWidgetContents)
        self.del_link.setObjectName("del_link")
        self.gridLayout.addWidget(self.del_link, 0, 2, 1, 1)
        self.listWidget = QtWidgets.QListWidget(self.dockWidgetContents)
        self.listWidget.setObjectName("listWidget")
        self.gridLayout.addWidget(self.listWidget, 2, 1, 1, 4)
        roadListDockWidget.setWidget(self.dockWidgetContents)

        self.retranslateUi(roadListDockWidget)
        QtCore.QMetaObject.connectSlotsByName(roadListDockWidget)

    def retranslateUi(self, roadListDockWidget):
        _translate = QtCore.QCoreApplication.translate
        roadListDockWidget.setWindowTitle(_translate("roadListDockWidget", "LINK列表"))
        self.up_link.setText(_translate("roadListDockWidget", "上移"))
        self.pick_link.setText(_translate("roadListDockWidget", "拾取"))
        self.down_link.setText(_translate("roadListDockWidget", "下移"))
        self.del_link.setText(_translate("roadListDockWidget", "删除行"))
