# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pickRoadName.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(398, 528)
        Dialog.setMinimumSize(QtCore.QSize(311, 0))
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.rid_tab_old = QtWidgets.QTableWidget(Dialog)
        self.rid_tab_old.setObjectName("rid_tab_old")
        self.rid_tab_old.setColumnCount(0)
        self.rid_tab_old.setRowCount(0)
        self.rid_tab_old.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout.addWidget(self.rid_tab_old)
        self.pick_road_btn = QtWidgets.QPushButton(Dialog)
        self.pick_road_btn.setObjectName("pick_road_btn")
        self.verticalLayout.addWidget(self.pick_road_btn)
        self.calc_road_btn = QtWidgets.QPushButton(Dialog)
        self.calc_road_btn.setObjectName("calc_road_btn")
        self.verticalLayout.addWidget(self.calc_road_btn)
        self.cancel_btn = QtWidgets.QPushButton(Dialog)
        self.cancel_btn.setObjectName("cancel_btn")
        self.verticalLayout.addWidget(self.cancel_btn)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "计算路口名称"))
        self.pick_road_btn.setText(_translate("Dialog", "拾取"))
        self.calc_road_btn.setText(_translate("Dialog", "计算"))
        self.cancel_btn.setText(_translate("Dialog", "取消"))
