# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ridListDockWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ridListDockWidget(object):
    def setupUi(self, ridListDockWidget):
        ridListDockWidget.setObjectName("ridListDockWidget")
        ridListDockWidget.resize(286, 464)
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.gridLayout = QtWidgets.QGridLayout(self.dockWidgetContents)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.dockWidgetContents)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout1 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout1.setObjectName("gridLayout1")
        self.lineEdit = QtWidgets.QLineEdit(self.tab)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout1.addWidget(self.lineEdit, 0, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.tab)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout1.addWidget(self.pushButton, 0, 1, 1, 1)
        self.listWidget1 = QtWidgets.QListWidget(self.tab)
        self.listWidget1.setObjectName("listWidget1")
        self.gridLayout1.addWidget(self.listWidget1, 1, 0, 1, 2)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout2 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout2.setObjectName("gridLayout2")
        self.listWidget2 = QtWidgets.QListWidget(self.tab_2)
        self.listWidget2.setObjectName("listWidget2")
        self.gridLayout2.addWidget(self.listWidget2, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        ridListDockWidget.setWidget(self.dockWidgetContents)

        self.retranslateUi(ridListDockWidget)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(ridListDockWidget)

    def retranslateUi(self, ridListDockWidget):
        _translate = QtCore.QCoreApplication.translate
        ridListDockWidget.setWindowTitle(_translate("ridListDockWidget", "RID列表"))
        self.pushButton.setText(_translate("ridListDockWidget", "查询"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("ridListDockWidget", "路段"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("ridListDockWidget", "路口"))
