# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'roadListDockWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_roadListDockWidget(object):
    def setupUi(self, roadListDockWidget):
        roadListDockWidget.setObjectName("roadListDockWidget")
        roadListDockWidget.resize(256, 464)
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.gridLayout = QtWidgets.QGridLayout(self.dockWidgetContents)
        self.gridLayout.setObjectName("gridLayout")
        self.listWidget = QtWidgets.QListWidget(self.dockWidgetContents)
        self.listWidget.setObjectName("listWidget")
        self.gridLayout.addWidget(self.listWidget, 2, 1, 1, 3)
        self.lineEdit = QtWidgets.QLineEdit(self.dockWidgetContents)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 1, 1, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.dockWidgetContents)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 1, 2, 1, 1)
        roadListDockWidget.setWidget(self.dockWidgetContents)

        self.retranslateUi(roadListDockWidget)
        QtCore.QMetaObject.connectSlotsByName(roadListDockWidget)

    def retranslateUi(self, roadListDockWidget):
        _translate = QtCore.QCoreApplication.translate
        roadListDockWidget.setWindowTitle(_translate("roadListDockWidget", "道路列表"))
        self.pushButton.setText(_translate("roadListDockWidget", "查询"))
